Repository MicrosoftDocs/quantum-docs, pull requests merged in 2022-04, with the labels that each got.

#513 Repo sync for protected CLA branch
  articles/user-guide/host-programs.md
  articles/user-guide/machines/full-state-simulator.md
  articles/user-guide/machines/index.md
  articles/user-guide/machines/noise-simulator.md
  articles/user-guide/machines/resources-estimator.md
  articles/user-guide/machines/sparse-simulator.md
  articles/user-guide/machines/toffoli-simulator.md
Labels: CLA, do-not-merge

#514 Repo sync for protected CLA branch
  articles/user-guide/machines/toc.yml
Labels: CLA, do-not-merge

#515 Repo sync for protected CLA branch
  articles/user-guide/libraries/standard/characterization.md
Labels: CLA, do-not-merge

#516 Repo sync for protected CLA branch
  articles/optimization-simulated-annealing.md
Labels: CLA, do-not-merge

#519 Repo sync for protected CLA branch
  articles/TOC.yml
  articles/optimization-which-solver-should-you-use.md
  articles/tutorial-qdk-quantum-random-number-generator.md
Labels: CLA, do-not-merge

#520 Repo sync for protected CLA branch
  articles/TOC.yml
  articles/how-to-publish-qio-job-as-azurefunction.md
  articles/how-to-publish-qsharp-job-as-azurefunction.md
  articles/media/honeywell-results.png
  articles/optimization-authenticate-managed-identity.md
  articles/optimization-authenticate-service-principal.md
  articles/user-guide/machines/sparse-simulator.md
Labels: CLA, do-not-merge

#522 Update README.md
  articles/README.md
  articles/release-notes.md
Labels: aq-pr-triaged, do-not-merge, review-team-triage, docs-editor-pilot

#524 Update release-notes.md
  articles/release-notes.md
Labels: do-not-merge, docs-editor-pilot

#527 Repo sync for protected CLA branch
  articles/azure-quantum-job-costs.md
  articles/get-started-jupyter-notebook.md
  articles/how-to-work-with-jobs.md
  articles/media/azure-quantum-flow-diagram-providers.png
  articles/media/azure-quantum-flow-diagram-providers.svg
  articles/media/azure-quantum-flow-diagram.png
  articles/overview-azure-quantum.md
  articles/pricing.md
  articles/provider-ionq.md
  articles/provider-quantinuum.md
  articles/quickstart-microsoft-cirq-portal.md
  articles/quickstart-microsoft-cirq.md
  articles/quickstart-microsoft-provider-format-portal.md
  articles/quickstart-microsoft-qiskit-portal.md
  articles/quickstart-microsoft-qiskit.md
Labels: CLA, do-not-merge

#528 Repo sync for protected CLA branch
  articles/contributing-style-guide.md
Labels: CLA, do-not-merge

#529 Repo sync for protected CLA branch
  .openpublishing.redirection.json
  articles/optimization-concepts-cost-functions.md
  articles/optimization-concepts-ising-model-for-optimization.md
  articles/optimization-population-annealing.md
  articles/optimization-substochastic-monte-carlo.md
  articles/user-guide/libraries/numerics/numerics.md
Labels: CLA, do-not-merge

#517 Quantinuum Provider Updates
  articles/provider-quantinuum.md
  articles/provider-support-quantinuum.md
Labels: aq-pr-triaged, do-not-merge, Change sent to author, azure-quantum/svc, computing/subsvc

#532 Repo sync for protected CLA branch
  articles/TOC.yml
  articles/how-to-manage-quantum-workspaces-with-azure-resource-manager.md
  articles/how-to-set-resource-locks.md
Labels: CLA, do-not-merge

#535 Repo sync for protected CLA branch
  articles/release-notes.md
Labels: CLA, do-not-merge
