Repository MicrosoftDocs/quantum-docs, pull requests merged in 2022-01, with the labels that each got.

#441 Repo sync for protected CLA branch
  articles/docfx.json
  articles/get-started-jupyter-notebook.md
  articles/how-to-run-notebooks-workspace.md
  articles/media/how-to-run-notebooks-workspace/notebook-gallery.gif
  articles/media/how-to-run-notebooks-workspace/notebook-gallery.png
  articles/media/how-to-run-notebooks-workspace/run-notebook.png
Labels: CLA

#448 Repo sync for protected CLA branch
  articles/TOC.yml
  articles/concepts-dirac-notation.md
  articles/concepts-open-systems.md
  articles/credits-faq.md
  articles/get-started-jupyter-notebook.md
  articles/how-to-create-workspace.md
  articles/includes/azure-quantum-credits.md
  articles/install-csharp-qdk.md
  articles/media/bloch-rho-mixed.png
  articles/media/bloch-rho-pure.png
  articles/media/ramsey-signal-ideal-model.png
  articles/media/ramsey-signal-noise-model.png
  articles/overview-azure-quantum.md
  articles/provider-ionq.md
Labels: CLA

#449 Repo sync for protected CLA branch
  articles/how-to-create-workspace.md
Labels: CLA

#453 Repo sync for protected CLA branch
  articles/includes/quickstart-cirq-include-honeywell.md
  articles/includes/quickstart-cirq-include-ionq.md
  articles/includes/quickstart-provider-include-honeywell.md
  articles/includes/quickstart-provider-include-ionq.md
  articles/includes/quickstart-qiskit-include-honeywell.md
  articles/includes/quickstart-qiskit-include-ionq.md
  articles/release-notes.md
Labels: CLA

#458 Repo sync for protected CLA branch
  .openpublishing.publish.config.json
Labels: CLA

#457 Add new param to tabu solver
  articles/optimization-tabu-search.md
Labels: doc-enhancement, aq-pr-triaged, ready-to-merge, Change sent to author

#456 Honeywell to quantinuum name change
  articles/TOC.yml
  articles/credits-faq.md
  articles/includes/quickstart-cirq-include-honeywell.md
  articles/includes/quickstart-provider-include-honeywell.md
  articles/includes/quickstart-qc-include-honeywell.md
  articles/includes/quickstart-qiskit-include-honeywell.md
  articles/media/logo-quantinuum.png
  articles/overview-azure-quantum.md
  articles/overview-understanding-quantum-computing.md
  articles/provider-honeywell.md
  articles/provider-support-honeywell.md
  articles/qc-target-list.md
  articles/quantum-computing-target-profiles.md
  articles/quickstart-microsoft-cirq.md
  articles/quickstart-microsoft-provider-format.md
  articles/quickstart-microsoft-qc.md
  articles/quickstart-microsoft-qiskit.md
  articles/release-notes.md
  articles/zone-pivot-groups.yml
Labels: doc-enhancement, aq-pr-triaged, ready-to-merge, Change sent to author, azure-quantum/svc, qdk/subsvc
