Repository MicrosoftDocs/quantum-docs, pull requests merged in 2022-03, with the labels that each got.

#479 Repo sync for protected CLA branch
  articles/how-to-create-workspace.md
  articles/media/add-provider-1.png
  articles/media/add-provider-2.png
Labels: CLA, do-not-merge

#480 Repo sync for protected CLA branch
  articles/release-notes.md
Labels: CLA, do-not-merge

#481 Repo sync for protected CLA branch
  articles/release-notes.md
Labels: CLA, do-not-merge

#483 Repo sync for protected CLA branch
  .openpublishing.publish.config.json
Labels: CLA, do-not-merge

#470 Equation example typo
  articles/concepts-dirac-notation.md
Labels: aq-pr-triaged, do-not-merge, Change sent to author, azure-quantum/svc, core/subsvc

#496 Repo sync for protected CLA branch
  articles/release-notes.md
Labels: CLA, do-not-merge

#497 Repo sync for protected CLA branch
  articles/includes/quickstart-provider-include-ionq.md
Labels: CLA, do-not-merge

#500 Repo sync for protected CLA branch
  .openpublishing.publish.config.json
Labels: CLA, do-not-merge

#502 Repo sync for protected CLA branch
  articles/user-guide/host-programs.md
Labels: CLA, do-not-merge

#498 Address Krysta's feedback on "Quickstart: Create a quantum-based random number generator in Azure Quantum"
  articles/includes/quickstart-qc-include-ionq.md
  articles/includes/quickstart-qc-include-quantinuum.md
Labels: aq-pr-triaged, do-not-merge, Change sent to author, azure-quantum/svc, computing/subsvc

#504 Repo sync for protected CLA branch
  articles/includes/azure-quantum-credits.md
  articles/overview-azure-quantum.md
  articles/release-notes.md
Labels: CLA

#506 Repo sync for protected CLA branch
  articles/tutorial-qdk-quantum-random-number-generator.md
Labels: CLA, do-not-merge

#493 Fix minor typo in media link
  articles/quickstart-microsoft-cirq-portal.md
  articles/quickstart-microsoft-qiskit-portal.md
Labels: aq-pr-triaged, do-not-merge, Change sent to author, azure-quantum/svc, qdk/subsvc

#508 Repo sync for protected CLA branch
  articles/azure-quantum-job-costs.md
  articles/concepts-open-systems.md
  articles/includes/pricing-optimization.md
  articles/includes/pricing-qc.md
  articles/pricing.md
  articles/provider-1qbit.md
  articles/provider-honeywell.md
  articles/provider-ionq.md
  articles/provider-microsoft-qio.md
  articles/provider-quantinuum.md
Labels: CLA, do-not-merge

#509 Repo sync for protected CLA branch
  articles/azure-quantum-common-issues.md
  articles/contributing-samples.md
  articles/how-to-csharp-qdk-local.md
  articles/how-to-publish-qsharp-job-as-azurefunction.md
  articles/includes/quickstart-qc-include-ionq.md
  articles/includes/quickstart-qc-include-quantinuum.md
  articles/install-binder-qdk.md
  articles/install-command-line-qdk.md
  articles/install-csharp-qdk.md
  articles/install-python-qdk.md
  articles/install-update-qdk.md
  articles/optimization-authenticate-service-principal.md
  articles/overview-azure-quantum.md
  articles/provider-honeywell-migration-guide.md
  articles/release-notes.md
  articles/user-guide/libraries/index.md
  articles/user-guide/libraries/machine-learning/basic-classification.md
  articles/user-guide/testing-debugging.md
Labels: CLA, do-not-merge
